apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
  labels:
    app: web
data:
  index.html: |
    <!doctype html>
    <html lang="en">
    <head><meta charset="utf-8"><title>ArgoCD Demo</title></head>
    <body style="font-family:Arial; text-align:center; padding:40px;">
      <h1>May and Amir! ðŸš€</h1>
      <p>Deployed via Argo CD from Git.</p>
    </body>
    </html>

